name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test:spelling
  test-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test:format
      - run: npm run test:algorithm-format
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test:build
  publish:
    if: github.ref == 'refs/heads/main'
    needs:
      - test-spelling
      - test-format
      - test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          cname: spec.graphql.org
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
